server {
    listen 80;
    server_name localhost;

    # Serve static files directly from the root directory
    location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico)$ {
        root /usr/share/nginx/html/dist;
        try_files $uri =404;
    }

    # Specific route for /edit_application to load edit_application.html for any parameters
    location ~ ^/edit_application(/.*)?$ {
        root /usr/share/nginx/html/dist;
        try_files /pages/edit_application.html =404;
    }

    location / {
        root /usr/share/nginx/html/dist;
        index index.html;
        try_files $uri $uri.html /pages$uri.html $uri/ /index.html;
    }

}
